from ctypes import c_void_p, c_int, c_uint16, c_char, c_uint64, Structure

WormContext = c_void_p
WormInfo = c_void_p
WormEntry = c_void_p
WormTransactionResponse = c_void_p

WormError = c_int
worm_uint = c_uint64

class WormRegisteredClients(Structure):
    _fields_ = [
        ("amount", c_int),
        ("clientIds", (c_char * 31) * 16),
        ]


(WORM_INIT_UNINITIALIZED,
WORM_INIT_INITIALIZED,
WORM_INIT_DECOMMISSIONED) = range(3)

# WormUserId
WORM_USER_UNAUTHENTICATED = 0
WORM_USER_ADMIN = 1
WORM_USER_TIME_ADMIN = 2
WORM_USER_LOGGER = 3          # neu in SDK v6 / TSE v2

WORM_EXPORT_TAR_INCREMENTAL_STATE_SIZE = 16

# ── Fehlercodes (vollständig gemäß SDK v6.0.0 wormError.h) ───────────────────
WORM_ERROR_NOERROR = 0
WORM_ERROR_INVALID_PARAMETER = 1
WORM_ERROR_NO_WORM_CARD = 2
WORM_ERROR_IO = 3
WORM_ERROR_TIMEOUT = 4
WORM_ERROR_OUTOFMEM = 5
WORM_ERROR_INVALID_RESPONSE = 6
WORM_ERROR_STORE_FULL_INTERNAL = 7
WORM_ERROR_RESPONSE_MISSING = 8
WORM_ERROR_EXPORT_NOT_INITIALIZED = 9
WORM_ERROR_EXPORT_FAILED = 10
WORM_ERROR_INCREMENTAL_EXPORT_INVALID_STATE = 11
WORM_ERROR_INCREMENTAL_EXPORT_NO_DATA = 12
WORM_ERROR_POWER_CYCLE_DETECTED = 13
WORM_ERROR_FIRMWARE_UPDATE_NOT_APPLIED = 14
WORM_ERROR_THREAD_START_FAILED = 15
WORM_ERROR_NETWORK = 16
WORM_ERROR_CMD_NOT_SUPPORTED = 17
WORM_ERROR_LAN_INVALID_API_TOKEN = 18
WORM_ERROR_NETWORK_TIMEOUT = 19
WORM_ERROR_CONNECTION_FAILED = 20
WORM_ERROR_LAN_UNBALANCED_LOCKS = 21
WORM_ERROR_LAN_INVALID_SERVER_RESPONSE = 22
WORM_ERROR_INVALID_STATE = 23
WORM_ERROR_TSE_NOT_FOUND = 24
WORM_ERROR_INCREMENTAL_EXPORT_LIMIT_TOO_LOW = 25
WORM_ERROR_FWU_NOT_AVAILABLE = 26

WORM_ERROR_FROM_CARD_FIRST = 0x1000
WORM_ERROR_UNKNOWN = 0x1001
WORM_ERROR_NO_TIME_SET = 0x1002
WORM_ERROR_NO_TRANSACTION_IN_PROGRESS = 0x1004
WORM_ERROR_INVALID_CMD_SYNTAX = 0x1005
WORM_ERROR_WRONG_LENGTH = WORM_ERROR_INVALID_CMD_SYNTAX   # deprecated alias
WORM_ERROR_NOT_ENOUGH_DATA_WRITTEN = 0x1006
WORM_ERROR_TSE_INVALID_PARAMETER = 0x1007
WORM_ERROR_TRANSACTION_NOT_STARTED = 0x1008
WORM_ERROR_MAX_PARALLEL_TRANSACTIONS = 0x1009
WORM_ERROR_CERTIFICATE_EXPIRED = 0x100A
WORM_ERROR_NO_LAST_TRANSACTION = 0x100C
WORM_ERROR_CMD_NOT_ALLOWED = 0x100D
WORM_ERROR_TRANSACTION_SIGNATURES_EXCEEDED = 0x100E
WORM_ERROR_NOT_AUTHORIZED = 0x100F
WORM_ERROR_MAX_REGISTERED_CLIENTS_REACHED = 0x1010
WORM_ERROR_CLIENT_NOT_REGISTERED = 0x1011
WORM_ERROR_EXPORT_UNACKNOWLEDGED_DATA = 0x1012
WORM_ERROR_CLIENT_HAS_UNFINISHED_TRANSACTIONS = 0x1013
WORM_ERROR_TSE_HAS_UNFINISHED_TRANSACTIONS = 0x1014
WORM_ERROR_TSE_NO_RESPONSE_TO_FETCH = 0x1015
WORM_ERROR_NOT_ALLOWED_EXPORT_IN_PROGRESS = 0x1016
WORM_ERROR_STORE_FULL = 0x1017
WORM_ERROR_CLIENT_ALREADY_REGISTERED = 0x1018          # neu SDK v6
WORM_ERROR_TSE_SEAPI_TRANSACTION_COUNTER_OVERFLOW = 0x1020
WORM_ERROR_TSE_SEAPI_SETTING_NEW_PIN_FAILED = 0x1021
WORM_ERROR_TSE_SEAPI_STORING_DATA_FAILED = 0x1022
WORM_ERROR_TSE_SEAPI_DISABLE_SECURE_ELEMENT_FAILED = 0x1023
WORM_ERROR_WRONG_STATE_NEEDS_PUK_CHANGE = 0x1050
WORM_ERROR_WRONG_STATE_NEEDS_PIN_CHANGE = 0x1051
WORM_ERROR_WRONG_STATE_NEEDS_ACTIVE_CTSS = 0x1053
WORM_ERROR_WRONG_STATE_NEEDS_ACTIVE_ERS = WORM_ERROR_WRONG_STATE_NEEDS_ACTIVE_CTSS  # deprecated
WORM_ERROR_WRONG_STATE_NEEDS_SELF_TEST = 0x1054
WORM_ERROR_WRONG_STATE_NEEDS_SELF_TEST_PASSED = 0x1055
WORM_ERROR_FWU_INTEGRITY_FAILURE = 0x1061
WORM_ERROR_FWU_DECRYPTION_FAILURE = 0x1062
WORM_ERROR_FWU_WRONG_FORMAT = 0x1064
WORM_ERROR_FWU_INTERNAL_ERROR = 0x1065
WORM_ERROR_FWU_DOWNGRADE_PROHIBITED = 0x1067
WORM_ERROR_TSE_ALREADY_INITIALIZED = 0x10FD
WORM_ERROR_TSE_DECOMMISSIONED = 0x10FE
WORM_ERROR_TSE_NOT_INITIALIZED = 0x10FF
WORM_ERROR_AUTHENTICATION_FAILED = 0x1100
WORM_ERROR_AUTHENTICATION_PIN_BLOCKED = 0x1201
WORM_ERROR_AUTHENTICATION_USER_NOT_LOGGED_IN = 0x1202
WORM_ERROR_TSE_SEAPI_AUTHENTICATION_PUK_TEMPORARILY_BLOCKED = 0x1203  # neu SDK v6
WORM_ERROR_SELF_TEST_FAILED_FW = 0x1300
WORM_ERROR_SELF_TEST_FAILED_CSP = 0x1310
WORM_ERROR_SELF_TEST_FAILED_RNG = 0x1320
WORM_ERROR_FWU_BASE_FW_ERROR = 0x1400
WORM_ERROR_FWU_FWEXT_ERROR = 0x1500
WORM_ERROR_FWU_CSP_ERROR = 0x1600
WORM_ERROR_TSE_SEAPI_AUTHENTICATION_WRONG_PUK = 0x1700  # neu SDK v6
WORM_ERROR_EXPORT_NONE_IN_PROGRESS = 0x2001
WORM_ERROR_EXPORT_RETRY = 0x2002
WORM_ERROR_EXPORT_NO_DATA_AVAILABLE = 0x2003
WORM_ERROR_CMD_NOT_FOUND = 0xF000
WORM_ERROR_TSE_SEAPI_FUNCTION_NOT_SUPPORTED = 0xF100
WORM_ERROR_TSE_SEAPI_GET_MAX_NUMBER_OF_CLIENTS_FAILED = 0xF101
WORM_ERROR_TSE_SEAPI_PARAMETER_TOO_LONG = 0xF103
WORM_ERROR_TSE_SEAPI_PARAMETER_SYNTAX = 0xF104
WORM_ERROR_TSE_SEAPI_GET_MAX_NUMBER_TRANSACTIONS_FAILED = 0xF106
WORM_ERROR_TSE_SEAPI_GET_REGISTERED_CLIENTS_FAILED = 0xF107
WORM_ERROR_TSE_SEAPI_GET_OPEN_TRANSACTIONS_FAILED = 0xF108
WORM_ERROR_TSE_SEAPI_GET_DESCRIPTION_FAILED = 0xF109
WORM_ERROR_TSE_SEAPI_SELF_TEST_FAILED = 0xF10A
WORM_ERROR_TSE_SEAPI_NO_DATA_AVAILABLE = 0xF10D
WORM_ERROR_TSE_SEAPI_INVALID_CLIENT_ID_CHARACTER = 0xF10F
WORM_ERROR_TSE_SEAPI_INVALID_TIME = 0xF110
WORM_ERROR_TSE_SEAPI_TRANSACTION_COUNTER_EXHAUSTED = 0xF112
WORM_ERROR_TSE_SEAPI_GET_CURRENT_TRANSACTION_COUNTER_FAILED = 0xF124
WORM_ERROR_TSE_SEAPI_REGISTER_CLIENT_FAILED = 0xF129
WORM_ERROR_TSE_SEAPI_DEREGISTER_CLIENT_FAILED = 0xF12A
WORM_ERROR_TSE_SEAPI_DEVICE_INITIALIZATION_FAILED = 0xF12B
WORM_ERROR_TSE_SEAPI_UPDATE_TIME_FAILED = 0xF12D
WORM_ERROR_TSE_SEAPI_DEVICE_UPDATE_FAILED = 0xF12E
WORM_ERROR_TSE_SEAPI_DELETE_LOG_MESSAGES_FAILED = 0xF130
WORM_ERROR_SIG_ERROR = 0xFF00
WORM_ERROR_TSE_SEAPI_STORING_LOG_MESSAGE_FAILED = 0xA016
WORM_ERROR_TSE_SEAPI_UNKNOWN_USER_ID = 0xA018
WORM_ERROR_TSE_SEAPI_SIGNATURE_COUNTER_OVERFLOW = 0xFF02
WORM_ERROR_TSE_SEAPI_SIGNING_EVENT_DATA_FAILED = 0xFF03
WORM_ERROR_TSE_SEAPI_RETRIEVE_LOG_MESSAGE_FAILED = 0xFF04
WORM_ERROR_FROM_CARD_LAST = 0xFFFF
